export default function PageLayout({ children }) {
    return <Head>
        <title>aprendiedno next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
}