import Head from "next/head";

export default function About() {
    return <>
        <Head>
            <title>Create Next</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header><h1>ahora si nos vamos a la pagina de about se mostrara head hecho en el componente de about</h1></header>
        <h1>esta es la pagina del about</h1>
    </>
}