import Head from 'next/head'
import styles from '../styles/NavBar.module.css'
import WebContent from '../components/WebContent'
import { useSelector, useDispatch } from 'react-redux'
import { useState, useEffect } from 'react'
import { getNavbarData } from '../store/slices/navbar.slice'
import { setLanguage } from '../store/slices/language.slice'
import Products from '../components/Products'
import Legals from '../components/Legals'
import Prefooter from '../components/Prefooter'
import Footer from '../components/Footer'


export default function Home() {
  const [idioma, setIdioma] = useState('es')
  const navText = useSelector(state => state.navbar)
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getNavbarData())
  }, [])

  // const updateLanguage = (e) => {
  //   e.preventDefault()
  //   dispatch(setLanguage(idioma))
  //   const selectLanguage = e.target.value
  //   setIdioma(selectLanguage)
  // }

  const english = () => {
    setIdioma('en')
    dispatch(setLanguage(idioma))
  }

  const spanish = () => {
    setIdioma('es')
    dispatch(setLanguage(idioma))
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>XCARET landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

        <nav className={styles.nav}>
          <img className={styles.logo} src={navText?.[`${idioma}`]?.navbar.logo} alt="logo" />
          <div className={styles.text__container}>

            <p>{navText?.[`${idioma}`]?.navbar.menu.contact}</p>
            {/* <select name="lan" onChange={(e) => updateLanguage(e)}>
            <option value='es'>es</option>
            <option value='en'>en</option>
          </select> */}
            <div>
              <span className={styles.language} onClick={english}>en</span>
              <br />
              <span className={styles.language} onClick={spanish}>es</span>
            </div>
            <select className={styles.select__nav} name="currency" >
              {navText?.[`${idioma}`]?.navbar.menu.currency.map(curr => (
                <option key={curr} value={curr}>{curr}</option>
              ))}
            </select>
          </div>
        </nav>
      </header>
      <WebContent navText={navText} idioma={idioma} />
      <Products navText={navText} idioma={idioma} />
      <Legals navText={navText} idioma={idioma} />
      <Prefooter navText={navText} idioma={idioma} />
      <Footer navText={navText} idioma={idioma} />
    </div>
  )
}
