import Head from 'next/head'
import styles from '../styles/NavBar.module.css'
import WebContent from '../components/WebContent'
import { useSelector, useDispatch } from 'react-redux'
import { useState, useEffect } from 'react'
import { getNavbarData } from '../store/slices/navbar.slice'
import { setLanguage } from '../store/slices/language.slice'
import Products from '../components/Products'


export default function Home() {
  const [idioma, setIdioma] = useState('es')
  const navText = useSelector(state => state.navbar)
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getNavbarData())
  }, [])

  const updateLanguage = (e) => {
    e.preventDefault()
    const selectLanguage = e.target.value
    setIdioma(selectLanguage)
    dispatch(setLanguage(idioma))
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>XCARET landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <img className={styles.logo} src={navText?.[`${idioma}`]?.navbar.logo} alt="logo" />
        <div className={styles.text__container}>

          <h3>{navText?.[`${idioma}`]?.navbar.menu.contact}</h3>
          <select name="lan" onChange={(e) => updateLanguage(e)}>
            <option value='es'>es</option>
            <option value='en'>en</option>
          </select>
          <select name="currency" >
            {navText?.[`${idioma}`]?.navbar.menu.currency.map(curr => (
              <option key={curr} value={curr}>{curr}</option>
            ))}
          </select>
        </div>
      </nav>
      <WebContent navText={navText} idioma={idioma} />
      <div className={styles.products__container}>

        <Products navText={navText} idioma={idioma} />

      </div>

    </div>
  )
}
