import Head from 'next/head'
import styles from '../styles/NavBar.module.css'
import xArte from '../public/xArte.png'
import xMexico from '../public/xMexico.png'
import xPlaya from '../public/xPlaya.png'
import { useEffect } from 'react'
import { getNavbarData } from '../store/slices/navbar.slice'
import { setLanguage } from '../store/slices/language.slice'
import { useSelector, useDispatch } from 'react-redux'
import WebContent from '../components/WebContent'
import Products from '../components/Products'
import Legals from '../components/Legals'
import Prefooter from '../components/Prefooter'
import Footer from '../components/Footer'


export default function Home() {


  const navText = useSelector(state => state.navbar)
  const language = useSelector(state => state.language)


  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getNavbarData())
  }, [])



  // const updateLanguage = (e) => {
  //   e.preventDefault()
  //   dispatch(setLanguage(idioma))
  //   const selectLanguage = e.target.value
  //   setIdioma(selectLanguage)
  // }

  const english = () => {

    dispatch(setLanguage('en'))
  }

  const spanish = () => {
    dispatch(setLanguage('es'))

  }




  return (
    <div className={styles.container}>
      <Head>
        <title>XCARET landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

        <nav className={styles.nav}>
          <img className={styles.logo} src={navText?.[`${language}`]?.navbar.logo} alt="logo" />
          <div className={styles.text__container}>

            <p>{navText?.[`${language}`]?.navbar.menu.contact}</p>
            {/* <select name="lan" onChange={(e) => updateLanguage(e)}>
            <option value='es'>es</option>
            <option value='en'>en</option>
          </select> */}
            <div>
              <span className={styles.language} onClick={english}>en</span>
              <br />
              <span className={styles.language} onClick={spanish}>es</span>
            </div>
            <select className={styles.select__nav} name="currency" >
              {navText?.[`${language}`]?.navbar.menu.currency.map(curr => (
                <option key={curr} value={curr}>{curr}</option>
              ))}
            </select>
          </div>
        </nav>
      </header>
      <WebContent />


      <Products hotel={'HOTEL XCARET ARTE'} imgLogo={xArte} />
      <Products hotel={'HOTEL XCARET MEXICO'} imgLogo={xMexico} />
      <Products hotel={'LA CASA DE LA PLAYA'} imgLogo={xPlaya} />

      <Legals />
      <Prefooter />
      <Footer />
    </div>
  )
}
